### ISSUE TITLE
Allow specifying features for the installed crates

### ISSUE THREAD

**Issue by Razican** [actions-rs/install#1]
## Motivation

I currently use this line in my workflows:
```
cargo install --features postgres --no-default-features diesel_cli
```

This action currently doesn't allow specifying features (or removing default features) of a crate, and that would be nice.

## Workflow example

```yaml
on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: diesel_cli
          version: latest
          features: postgres
          default-features: false
      - run: diesel migration run
```

## Additional context

If we want to also support cache for this, we would need to add cache for different feature matrices, which might prove difficult.
