### ISSUE TITLE
Support installing crates using Git URLs

### ISSUE THREAD

**Issue by mandrean** [actions-rs/install#10]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

As an `action-rs/install` user, it would be useful to have the ability to also install crates using Git URLs, and not just crates published on crates.io.

**Also it would match the actual `cargo install` command better, since it has the `--git`/`--branch`/`--tag`/`--rev` flags precisely for this purpose.**

One use-case for example is old, unmaintained crates with a new fork that doesn't have its own published crate.

## Workflow example

```yaml
- uses: actions-rs/install@v0.1
  with:
    crate: cargo-audit
    version: latest
    git: https://github.com/RustSec/cargo-audit
    use-tool-cache: true
```
```yaml
- uses: actions-rs/install@v0.1
  with:
    crate: cargo-audit
    version: latest
    git:
      repo: https://github.com/RustSec/cargo-audit
      branch: master
      tag: v0.12.1
      # rev: d3017c3
    use-tool-cache: true
```
