### ISSUE TITLE
HTTP 403 from the tool cache

### ISSUE THREAD

**Issue by torhovland** [actions-rs/install#12]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

When actions-rs/install@v0.1 tries to download a crate from the tools cache, it gets an Unexpected HTTP response: 403.

## Workflow code

```yaml
name: Deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust tools
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true

      - name: Install Trunk
        uses: actions-rs/install@v0.1
        with:
          crate: trunk
          version: latest
          use-tool-cache: true
```
 
## Action output

```
Run actions-rs/install@v0.1
  with:
    crate: trunk
    version: latest
    use-tool-cache: true
    use-cache: true
Tool cache is explicitly enabled via the Action input
Downloading from the tool cache
  Newest trunk version available at crates.io: 0.8.2
  Downloading trunk signature into /tmp/trunk.zip.sig
  Warning: Unable to download trunk == latest from the tool cache: Error: Unexpected HTTP response: 403
```

## Expected behavior

That Trunk got quickly installed using the tool cache.
