### ISSUE TITLE
Strange freeze when installing sccache

### ISSUE THREAD

**Issue by Veetaha** [actions-rs/install#3]
## Description

The bug I am seeing is that once I push commits to a PR, the install action freezes for indefinite amount of time (IIRC it will bail after 5+ hours of freeze but I cant find this run anymore...)

Here is a recent run, sorry the project is private, I can't give a link to the workflow.
After 25 minutes of idling I canceled the workflow and here are the logs:

![image](https://user-images.githubusercontent.com/36276403/79991608-2c95ff80-84bb-11ea-8d1a-8394b853ec86.png)

## Workflow code
```yaml
    - name: Cache sccache cache
      uses: actions/cache@v1
      with:
        path: ${{ env.SCCACHE_DIR }}
        key: sccache-cache-${{ hashFiles('**/Cargo.toml') }}
    - name: Install sccache
        uses: actions-rs/install@v0.1.2 
        with:
          crate: sccache
          use-tool-cache: true
          version: latest
```

 
<details>
<summary>Textual logs</summary>

```
Run actions-rs/install@v0.1
Tool cache is explicitly enabled via the Action input
Downloading from the tool cache
  Newest sccache version available at crates.io: 0.2.13
  Downloading sccache signature into /tmp/sccache.zip.sig
  Downloading sccache == 0.2.13 into /tmp/sccache.zip
  Starting signature verification process
  /usr/bin/openssl dgst -sha256 -verify /home/runner/work/_actions/actions-rs/install/v0.1/public.pem -signature /tmp/sccache.zip.sig /tmp/sccache.zip
  Verified OK
  Extracting files into /home/runner/.cargo/bin
  /usr/bin/unzip /tmp/sccache.zip
  Archive:  /tmp/sccache.zip
  replace sccache? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
  ##[error]The operation was canceled.
```
</details>

What is interesting is that after canceling workflow and hitting the `rerun` button everything works fine.
I suppose the problem is that there is a call to unzip utility that is run in interactive mode...
