### ISSUE TITLE
Action fails if binary already exists

### ISSUE THREAD

**Issue by fengyc** [actions-rs/install#6]
## Description

Github action fails if binary already exists.

## Workflow code

```yaml
    - name: Rust install cargo-deb
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-deb
        version: latest
```
 
## Action output

```
  Newest cargo-deb version available at crates.io: 1.24.0
  Downloading cargo-deb signature into /tmp/cargo-deb.zip.sig
  Downloading cargo-deb == 1.24.0 into /tmp/cargo-deb.zip
  Starting signature verification process
  /usr/bin/openssl dgst -sha256 -verify /home/runner/work/_actions/actions-rs/install/v0.1/public.pem -signature /tmp/cargo-deb.zip.sig /tmp/cargo-deb.zip
  Verified OK
  Extracting files into /home/runner/.cargo/bin
  /usr/bin/unzip /tmp/cargo-deb.zip
  Archive:  /tmp/cargo-deb.zip
  replace cargo-deb? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
  ##[error]The operation was canceled.
```

## Expected behavior

Need an option to ignore/replace binary if it exits.
