### ISSUE TITLE
Install using specific rustc version

### ISSUE THREAD

**Issue by jhpratt** [actions-rs/install#9]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.
  _Possibly! It depends how much free time I have._

## Motivation

I'd like to be able to install tools like `cargo-web` and `cargo-hack` and be able to use them even on older compilers. To do this, the tools need to be installed using a more recent rustc (typically stable is more than sufficient), as the tools have a different MSRV than the code I'm testing.

## Workflow example

```yaml
on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          rustc: stable
      - run: cargo audit
```

This would be equivalent to performing `cargo +stable install cargo-audit`.

I don't know if/how this would interact with the toolchain cache.
